### PR TITLE
Transformers bounds

### PR DESCRIPTION
**Pull request by timmytofu**
Adds transformers-compat and widens the bounds on transformers to allow for older versions.

### CODE REVIEW

**Comment by timmytofu** [comment]
I should mention I tried installing it with transformers forced at 0.3.* and it compiled, tests passed, and I haven't hit anything weird as I've been playing around with it.

**Comment by asilvestre** [comment]
Thank you very much. I'll change the transformers requirement to >= 0.3 too and I'll upload it to hackage.

**Comment by asilvestre** [comment]
I've tried forcing transformers to 0.3.* and I couldn't get it to work, first it conflicts with mtl's 2.2 requirement of transformers >= 0.4 and if I downgrade the requirements for mtl I still get compilation errors in the lib's code.
For now I'll leave it with you changes, but if you have any suggestion about what I might be doing wrong I'll try it again.

**Comment by timmytofu** [comment]
Ah, you're right, I must've not reconfigured after setting it to `== 0.3.*`. I was able to get it to work with `mtl >= 2.1` instead of 2.2, though. It seems to work for me, I'll open another pull request but you'd know better than me if this causes any problems.
